[package]
name = "csv_converter"
version = "0.1.0"
edition = "2021"

[lib]
name = "csv_converter"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
rust_xlsxwriter = "0.93.0"
csv = "1.3.0"
